config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get 'home', to: 'home#index'

  resources :contents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user

  has_many :tag_contents, dependent: :destroy
  has_many :tags, through: :tag_contents

  validates :title, :description, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user

  has_many :tag_contents, dependent: :destroy
  has_many :contents, through: :tag_contents

  validates :name, presence: true, uniqueness: { scope: :user_id}
end

app/models/tag_content.rb
class TagContent < ApplicationRecord
  belongs_to :tag
  belongs_to :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tags
  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_content, only: %i[ show edit update destroy ]
  def index
    @contents = current_user.contents
    @contents = @contents.joins(:tags).where(tags: { name: params[:tags]}).distinct if params[:tags].present?
  end
  # GET /contentS/1 or /contentS/1.json
  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
  end

  def new
    @content = Content.new
  end

  def edit
  end

  def create
    @content = current_user.contents.build(content_params)
    if @content.save
      associate_tags!
      redirect_to contents_path, notice: "Content successfully created!"
    else
      render :new
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        associate_tags!
        format.html { redirect_to @content, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_path, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  def tags_params
    params.require(:content).permit(tags: [])[:tags].reject(&:blank?)
  end

  def content_params
    params.require(:content).permit(:title,:description)
  end

  def associate_tags!
    tags = tags_params.map do |tag_name|
      current_user.tags.where(name: tag_name).first_or_initialize
    end
    @content.tags = tags
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @tag_data = current_user.contents.joins(:tags).group('tags.name').count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contents/_form.html.erb
<% if @content.errors.any? %>
  <%=@content.errors.full_messages.join(', ') %>
<% end %>
<%= form_with(model: @content, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title%>
    <%=form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description%>
    <%=form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :tags %>
    <%=form.select :tags, options_for_select(current_user.tags.pluck(:name), @content.tags.pluck(:name)),{},
                   {class:'form-control select2', multiple: 'multiple'} %>
  </div>

  <div class="actions">
    <%=form.submit 'Save', class:'btn btn-primary'%>
    <%= link_to 'Back', contents_path %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Edit Content</h1>
<%=render 'form' %>

app/views/contents/index.html.erb
<%= form_tag(contents_path,method: :get) do %>
  <div class="form-group">
    <%= label_tag :tags %>
    <%=select_tag 'tags[]', options_for_select(current_user.tags.pluck(:name), params[:tags]),class:'select2 form-control', multiple: 'multiple'%>
  </div>
  <div class="actions">
    <%=submit_tag('Search',class:'btn btn-primary') %>
    <%=link_to "New Content", new_content_path,class:'btn btn-info' %>
  </div>
<% end %>
<div class="page-header">
  <h1><%=t 'Contents' %></h1>
</div>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Tags</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%@contents.each do |contents| %>
      <tr>
        <td><%=contents.title %></td>
        <td><%=contents.description %></td>
        <td><%=contents.tags.pluck(:name).join(', ') %></td>
        <td>
          <%= link_to content_tag(:i,nil, class: ["fa", "fa-eye"]),
                      content_path(contents), :class => 'btn btn-success btn-xs' %>
          <%= link_to content_tag(:i,nil, class: ["fa", "fa-edit"]),
                      edit_content_path(contents), :class => 'btn btn-primary btn-xs' %>
          <%= link_to content_tag(:i,nil, class: ["fa", "fa-trash"]),
                      content_path(contents), :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contents/new.html.erb
<h1>New Content</h1>
<%=render 'form' %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @content.title %>
</p>

<p>
  <strong>Descricao:</strong>
  <%=raw @markdown.render(@content.description) %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/home/index.html.erb
<h1>Cloud Tags</h1>
<%@tag_data.each do |tag_name, count| %>
  <span style='font-size: <%=count * 20%>px'>
    <%=link_to tag_name, contents_path(tags:[tag_name]), style: 'text-decoration: none'%>
  </span>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Mind Tag', root_url, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%=link_to 'Contents',contents_path, class: "nav-link"%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%=link_to 'Logout',destroy_user_session_path,class:'btn btn-outline-success my-2 my-sm-0', method: :delete %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MindTag</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Custom fonts for this template-->
    <!-- Custom fonts for this template -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">


  </head>

  <body>
  <% if user_signed_in? %>
    <%= render 'layouts/header' %>
  <% end %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>